
rm(list=ls())
install.packages('gt')
library(DBI)
library(dbplyr)
library(duckdb)
library(readxl)
library(writexl)
library(googlesheets4)
library(tidyverse)
library(janitor) ##clean_names()

options(tibble.width=Inf)

set.seed(1)

df <- read_xlsx('comp646_sa.xlsx')
df

clean_names(df)

df |> 
  mutate(quantity = parse_number(quantity))


sum(is.na(df['customer_id']))
#2. Compute the revenue stream for each item (row) using unit_price ∗ quantity. 
#Then aggregate the revenues by country and sort them in descending order by gross revenue.

df_country <-
df |> 
  mutate(quantity = parse_number(quantity),
          revenue = unit_price *quantity) |> 
  group_by(country) |> 
  summarize(total_sales = sum(revenue)) |> 
  arrange(desc(total_sales))

df_country
#3. Create a bar chart using ggplot2 that displays sales by country in descending order. 
# Which country generates the highest revenue for the company?
ggplot(df_country, aes(x = country, y = total_sales)) + 
  geom_col()

#   4. What does the following function do, and what is its expected output?
df<- 
  df |> 
  mutate(revenue = unit_price*parse_number(quantity))
daily_sales<-
  function(data, selected_country=
           'New Zealand') {
  data$days = as.character(data$days)
  data |>
    filter(country == selected_country) |>
    select(country, year, month, days, revenue) |>
    group_by(days) |>
    summarize(daily_revenue = sum(revenue)) |>
    mutate(days = parse_number(days)) |>
    arrange(days)
}
# function to summarize selected country each day's total sales, and order by days asecding.
# results return nothing, as there is no sale data for New Zealand
df |>
  daily_sales()

# 5. Use the function and create a ggplot chart for output with respect to the United Kingdom.
df |> 
  daily_sales('United Kingdom') |> 
  ggplot(aes(x=days, y=daily_revenue))+
  geom_col()

#6. Calculate the total revenue generated by each customer. 
# Who is our top customer- the one generating the highest revenue?
# customer_id=14646 has the highest revenue


df |> 
  drop_na(customer_id) |> 
  group_by(customer_id) |> 
  summarize(total = sum(revenue,na.rm = TRUE)) |> 
  arrange(desc(total))

#7. Calculate the revenue for each invoice. Which invoice generated the highest revenue?
# invoice_no =541431 has the highest revenue
df |> 
  group_by(invoice_no) |> 
  summarize(total = sum(revenue)) |> 
  arrange(desc(total)) |> 
  slice(1)

# 8. It seems unusual that the highest invoice revenue exceeds the revenue from our top customer.
#Why does this seem odd? Filter the data for:
 # • the invoices of the customer who generated the highest overall revenue, and
# • the invoice with the highest individual revenue.
df |> 
  filter(customer_id == 12346) 


df |> 
  filter(invoice_no == 541431)

#Then explain why this outcome actually makes sense- 
#that an individual invoice can have higherrevenue than the total revenue from a single customer 
# because that invoice got cancelled, when cancelled, it has a C in front of invoice_no, but for that customer, the toal revenue is 0

